# Hugo config.toml that controls variables for this website.
# For more info, see https://gohugo.io/getting-started/configuration/
baseURL = "https://ross.gg/"
title = "Ross Jacobs"
subtitle = "Herder of 1s and 0s"
languageCode = "en-US"
DefaultContentLanguage = "en"
enableRobotsTXT = true
enableEmoji = true
theme = "even"

# Hugo
buildDrafts = false
enableGitInfo = true    # show
postNavigation = true
paginate = 5                                              
paginatedsections = ["post"]    # Number of blog posts in each pagination page

# Syntax highlighting by Chroma. NOTE: Don't enable `highlightInClient` and `chroma` at the same time!
pygmentsOptions = "linenos=table"
pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true

disqusShortname = ""      # disqus_shortname
googleAnalytics = "UA-143876903-1"

[sitemap]                 # essential                   
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]             # config your menu           
  name = "About"
  weight = 10
  identifier = "about"
  url = "/about"
[[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "/projects"
  weight = 15
[[menu.main]]
  name = "Archives"
  weight = 20
  identifier = "archives"
  url = "/post/"
[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"

[params]
  version = "4.x"           # Used to give a friendly message when you have an incompatible update

  since = "2019"            # Site creation time          
  # use public git repo url to link lastmod git commit, enableGitInfo should be true.
  gitRepo = "https://github.com/pocc/swit.sh"
  author = "Ross Jacobs"

  # site info (optional)                                
  logoTitle = "Ross Jacobs"        # default: the title value 
  #keywords = ["Hugo", "theme","even"]
  description = "Ross Jacobs' personal website"

  # paginate of archives, tags and categories             
  archivePaginate = 50

  # show 'xx Posts In Total' in archive page ?            
  showArchiveCount = false

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  # show word count and read time ?                       
  moreMeta = true

  # Syntax highlighting by highlight.js
  highlightInClient = false

  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  toc = true                                                                            
  autoCollapseToc = false   # Auto expand and collapse toc                              
  fancybox = true           # see https://github.com/fancyapps/fancybox                 

  contentCopyright = '(C) Ross Jacobs'     # e.g. '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

  [params.social]                                    
    a-email = "mailto:rj@swit.sh"
    b-stack-overflow = "1596750"
    e-linkedin = "rossbjacobs"
    g-github = "http://github.com/pocc"

# See https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true      # 12.214.31.144 -> 12.214.31.0
  [privacy.youtube]
    privacyEnhanced = true

# see https://gohugo.io/getting-started/configuration-markup
[markup]
  [markup.tableOfContents]
    startLevel = 1
  [markup.goldmark.renderer]
    unsafe = true

