# Site Vars
baseURL = "https://swit.sh"
title = "Ross Jacobs" # Homepage title and page title suffix
subtitle = "Herder of 1s and 0s"
buildDrafts = false
languageCode = "en-US" # Controls site language
DefaultContentLanguage = "en"
disableLiveReload = false # Optional, set true to disable live reload
enableRobotsTXT = true # Suggested, enable robots.txt file
enableGitInfo = true

# Controls default theme and theme components
theme = [
  "fractal-forest", # OBSD
  "after-dark" # AGPL-3.0-or-later
]

# Layout
copyright = "Copyright &copy; 2019 Ross Jacobs. Licensed under <a target=\"_blank\" rel=\"external noopener license\" href=\"https://www.apache.org/licenses/LICENSE-2.0\">Apache 2.0</a>."
paginate = 10 # Number of posts to show before paginating
pygmentsCodefences = true # Suggested, highlight fenced code blocks
pygmentsUseClasses = true # Required for custom syntax highlighting
PygmentsStyle = "monokai"
# sectionPagesMenu = "main" # Enable menu system for lazy bloggers
# footnoteReturnLinkContents = "↩" # Provides a nicer footnote return link
#[params.layout.menu.main]
#  hidden = false # Optional, set false or remove to show section menu

[[menu.main]]
  name = "home"
  weight = 1
  identifier = "index"
  url = "/"
[[menu.main]]
  name = "projects"
  weight = 2
  identifier = "projects"
  url = "/projects/"
[[menu.main]]
  name = "tshark.dev"
  weight = 3
  identifier = "tshark_dev"
  url = "/tshark_dev/"
[[menu.main]]
  name = "posts"
  weight = 4
  identifier = "posts"
  url = "/post"

[params]
  description = "Personal Website" # Suggested, controls default description meta
  author = "Ross Jacobs" # Optional, controls author name display on posts
  has_cookies = false # Optional, set true to disable cookie disclaimer
  hide_author = false # Optional, set true to hide author name on posts
  disable_csp = false # Optional, set true to disable content security policy
  [[layout.home]]
    hide_blog = true

[params.layout.footer]
  hidden = false # Optional, set true to hide footer

[params.modules.fractal_forest]
  enabled = true # Optional, set false to disable module
  decoders = ["bpgdec8a"] # Optional, 8-bit javascript decoder with animation
