baseURL = "/"
title = "Ross Jacobs"
subtitle = "Subtitle (If you see this, this is an ERROR!)"

# Current theme (multiple here to test their looks)
#theme = "hyde-hyde"
#theme = "bilberry-hugo-theme"
#theme = "Hugo-Octopress"
#theme = "gohugo-theme-ananke"
#theme = "hugo-coder"
theme = "hugo-theme-casper"

#disablePathToLower = False
copyright = "Copyright © 2019, all rights reserved."
languageCode = "en"
DefaultContentLanguage = "en"
postNavigation = true

# Disqus shortcode
# Disable comments for any individual post by adding "comments: false" in its frontmatter
disqusShortname = "Your disqus shortname"

# Setting a value will load highlight.js and enable syntax highlighting using the style selected.
# See https://github.com/isagalaev/highlight.js/tree/master/src/styles for available styles
# A preview of above styles can be viewed at https://highlightjs.org/static/demo/
hjsStyle = "default"

# Number of blog posts in each pagination page
paginatedsections = ["posts"]
paginate = 6

# Adhere to post format below
canonifyurls = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    # Will render on some layouts
    pre = "<i class='fas fa-newspaper'></i>"
    post = "<span class='alert'>New!</span>"
    url = "/posts/"
    weight = -120
#  [[menu.main]]
#    identifier = "portfolio"
#    name = "portfolio"
#    url = "/portfolio/"
#    weight = -110
  [[menu.main]]
    identifier = "about"
    name = "about"
    # Will render on some layouts
	pre = "<i class='fas fa-newspaper'></i>"
    url = "/about/"
    weight = -100

[params]
  description = "Writes Software"
  # metadescription = "Used as 'description' meta tag for both home and index pages. If not set, 'description' will be used instead"
  cover = "images/lorem_ipsum_background.jpg"
  logo = "images/rj.jpg"
  author = "Ross Jacobs"
  authorlocation = "San Francisco, United States"
  authorwebsite = "https://swit.sh"
  authorbio= "my bio"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = "http://feeds.feedburner.com/..."
  githubName = "pocc"
  linkedinName = "rossbjacobs"
  email = "rj@swit.sh"
  # twitterName = ""
  # facebookName = ""
  # codepenName = ""
  # stackoverflowId = ""
  # keybaseName = ""
  # flickrName = ""
  # instagramName = ""
  # pinterestName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  
