[build]
publish = "public"
command = "hugo --minify --gc"

[context.production.environment]
HUGO_VERSION = "0.55.6"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --minify --gc --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.55.6"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --minify --gc --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.55.6"

[context.branch-deploy]
command = "hugo --minify --gc -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.55.6"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
